config_version: 40

models:
  - name: test38flash0911
    use: langchain_openai:ChatOpenAI
    model: qwen3.8-max
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key: sk-ws-H.PDXMIXL.Y9wp.MEQCIBcwExauEMFMo5koPmunvVnDY3ZW6mOWGnq6Duv7dKF8AiB51J_xcYOjg12w5niVsi6KuEt5YhdBv9nzTt94TFK8qQ

sandbox:
  use: deerflow.sandbox.local:LocalSandboxProvider

tools:
  - name: web_search
    group: web
    use: deerflow.community.ddg_search.tools:web_search_tool
  - name: read_file
    group: file:read
    use: deerflow.sandbox.tools:read_file_tool
  - name: write_file
    group: file:write
    use: deerflow.sandbox.tools:write_file_tool
